name: product_manager
description: "서연이화 초중품관리앱"
publish_to: 'none'
version: 0.0.1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.17
  hive_flutter: ^1.1.0
  encrypt: ^5.0.3
  dio: ^5.8.0+1
  flutter_native_splash: ^2.4.4
  permission_handler: ^11.4.0
  intl: ^0.19.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.0
  flutter_pdfview: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/env/
    - assets/images/
    - assets/images/ico/
    - assets/images/bg/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700